import React, { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity, Modal, ActivityIndicator } from 'react-native';
import { useEventTypesStore } from '../store/eventTypes';
import { Ionicons } from '@expo/vector-icons';
import dayjs from 'dayjs';
import DateTimePicker from '@react-native-community/datetimepicker';
import { createCalendarEvent } from '../services/calendarService';
import { useSettingsStore } from '../store/settings';

interface Props {
    visible: boolean;
    onClose: () => void;
    event: {
        title: string;
        start: Date;
        end: Date;
        color?: string;
    } | null;
    onEventCreated?: () => void;
}

export function LunchContextModal({ visible, onClose, event, onEventCreated }: Props) {
    const { lunchConfig } = useEventTypesStore();
    const { visibleCalendarIds, timeFormat } = useSettingsStore(); // Added timeFormat
    const timeFormatStr = timeFormat === '24h' ? 'HH:mm' : 'h:mm A'; // Derived format

    // Internal state for edits
    const [start, setStart] = useState<Date>(new Date());
    const [end, setEnd] = useState<Date>(new Date());
    const [isMaterializing, setIsMaterializing] = useState(false);
    const [showStartPicker, setShowStartPicker] = useState(false);
    const [showEndPicker, setShowEndPicker] = useState(false);

    useEffect(() => {
        if (event) {
            setStart(new Date(event.start));
            setEnd(new Date(event.end));
        }
    }, [event, visible]);

    if (!event) return null;

    const handleMaterialize = async () => {
        // Optimistic UI: Close immediately
        onClose();

        try {
            // Determine target calendar
            let targetCalendarId = lunchConfig?.targetCalendarId;

            // Fallback to first visible calendar if not configured
            if (!targetCalendarId && visibleCalendarIds.length > 0) {
                targetCalendarId = visibleCalendarIds[0];
            }

            if (!targetCalendarId) {
                console.error('[LunchContextModal] No target calendar found.');
                alert('Please select a target calendar in Lunch settings or enable at least one calendar.');
                return; // Can't proceed
            }

            // Ensure dates are Date objects
            const startDate = new Date(start);
            const endDate = new Date(end);

            const eventData: any = {
                title: 'Lunch',
                startDate,
                endDate,
                timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                notes: 'Generated by AI Inbox'
            };

            // Add Default Invitee if present
            if (lunchConfig?.defaultInvitee) {
                eventData.attendees = [{
                    email: lunchConfig.defaultInvitee,
                    role: 'attendee',
                    status: 'pending',
                    type: 'person'
                }];
            }

            await createCalendarEvent(targetCalendarId, eventData);

            // Trigger refresh in parent
            if (onEventCreated) {
                onEventCreated();
            }

        } catch (error) {
            console.error('[LunchContextModal] Failed to materialize lunch:', error);
            // Since we closed the modal, we should use an Alert or Toast to notify failure.
            alert('Failed to materialize lunch event. Check logs.');
        }
    };

    const handleSave = () => {
        onClose();
    };

    const onChangeStart = (event: any, selectedDate?: Date) => {
        setShowStartPicker(false);
        if (selectedDate) {
            setStart(selectedDate);
            // Maintain duration if possible, or just clamp end?
            // Let's keep it simple: if start > end, move end
            if (selectedDate > end) {
                setEnd(dayjs(selectedDate).add(60, 'minute').toDate());
            }
        }
    };

    const onChangeEnd = (event: any, selectedDate?: Date) => {
        setShowEndPicker(false);
        if (selectedDate) {
            setEnd(selectedDate);
            if (selectedDate < start) {
                setStart(dayjs(selectedDate).subtract(60, 'minute').toDate());
            }
        }
    };

    return (
        <Modal
            animationType="fade"
            transparent={true}
            visible={visible}
            onRequestClose={onClose}
        >
            <TouchableOpacity
                className="flex-1 bg-black/60 justify-end"
                activeOpacity={1}
                onPress={onClose}
            >
                <TouchableOpacity
                    activeOpacity={1}
                    className="bg-slate-900 rounded-t-3xl p-6 border-t border-slate-700"
                >
                    <View className="flex-row justify-between items-center mb-6">
                        <View className="flex-row items-center gap-2">
                            <View
                                className="w-3 h-3 rounded-full"
                                style={{ backgroundColor: event.color || '#22c55e' }}
                            />
                            <Text className="text-white text-xl font-bold">Lunch (Suggested)</Text>
                        </View>
                        <TouchableOpacity onPress={onClose} className="p-2 bg-slate-800 rounded-full">
                            <Ionicons name="close" size={20} color="#94a3b8" />
                        </TouchableOpacity>
                    </View>

                    {/* Time Pickers */}
                    <View className="flex-row gap-4 mb-8">
                        <View className="flex-1">
                            <Text className="text-slate-400 text-xs font-bold uppercase mb-2">Start Time</Text>
                            <TouchableOpacity
                                onPress={() => setShowStartPicker(true)}
                                className="bg-slate-800 p-3 rounded-xl border border-slate-700"
                            >
                                <Text className="text-white font-mono text-center">
                                    {dayjs(start).format(timeFormatStr)}
                                </Text>
                            </TouchableOpacity>
                        </View>

                        <View className="flex-1">
                            <Text className="text-slate-400 text-xs font-bold uppercase mb-2">End Time</Text>
                            <TouchableOpacity
                                onPress={() => setShowEndPicker(true)}
                                className="bg-slate-800 p-3 rounded-xl border border-slate-700"
                            >
                                <Text className="text-white font-mono text-center">
                                    {dayjs(end).format(timeFormatStr)}
                                </Text>
                            </TouchableOpacity>
                        </View>
                    </View>

                    {showStartPicker && (
                        <DateTimePicker
                            value={start}
                            mode="time"
                            display="spinner"
                            onChange={onChangeStart}
                        />
                    )}

                    {showEndPicker && (
                        <DateTimePicker
                            value={end}
                            mode="time"
                            display="spinner"
                            onChange={onChangeEnd}
                        />
                    )}

                    {/* Actions */}
                    <View className="flex-row gap-3">
                        {/* Save (Close for now) */}
                        <TouchableOpacity
                            onPress={handleSave}
                            className="flex-1 bg-slate-800 p-4 rounded-xl items-center border border-slate-700"
                        >
                            <Text className="text-slate-300 font-bold">Save</Text>
                        </TouchableOpacity>

                        {/* Materialize */}
                        <TouchableOpacity
                            onPress={handleMaterialize}
                            disabled={isMaterializing}
                            className="flex-[2] bg-emerald-600 p-4 rounded-xl items-center flex-row justify-center gap-2"
                        >
                            {isMaterializing ? (
                                <ActivityIndicator color="white" size="small" />
                            ) : (
                                <>
                                    <Ionicons name="calendar" size={20} color="white" />
                                    <Text className="text-white font-bold text-base">Materialize</Text>
                                </>
                            )}
                        </TouchableOpacity>
                    </View>

                    <Text className="text-slate-500 text-center mt-4 text-xs">
                        Creates event in {lunchConfig?.targetCalendarId ? 'selected calendar' : 'default calendar'}
                    </Text>

                </TouchableOpacity>
            </TouchableOpacity>
        </Modal>
    );
}
