import React, { useState, useEffect } from 'react';
import { View, Text, Modal, TouchableOpacity, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import DateTimePicker from '@react-native-community/datetimepicker';
import dayjs from 'dayjs';
import { BlurView } from 'expo-blur';
import { useSettingsStore } from '../store/settings';
import { createCalendarEvent } from '../services/calendarService';
import { Colors, Palette } from './ui/design-tokens';
import { showAlert, showError } from '../utils/alert';
import { AppButton, CloseButton } from './ui/AppButton';

interface UnifiedSuggestionModalProps {
    visible: boolean;
    onClose: () => void;
    type: 'lunch' | 'walk';
    suggestion: {
        start: string | Date;
        end?: string | Date;
        reason?: string;
        title?: string;
    } | null;
    onEventCreated: () => void;
    onDismiss?: () => void; // For dismissing suggestions without creating
}

export function UnifiedSuggestionModal({ 
    visible, 
    onClose, 
    type, 
    suggestion, 
    onEventCreated, 
    onDismiss 
}: UnifiedSuggestionModalProps) {
    const { timeFormat, defaultCreateCalendarId, visibleCalendarIds, myEmails } = useSettingsStore();
    const timeFormatStr = timeFormat === '24h' ? 'HH:mm' : 'h:mm A';

    const [loading, setLoading] = useState(false);
    const [adjustedStart, setAdjustedStart] = useState<Date | null>(null);
    const [showPicker, setShowPicker] = useState(false);
    
    // Reset state when modal opens/closes
    useEffect(() => {
        if (visible) {
            setAdjustedStart(null);
            setLoading(false);
        }
    }, [visible]);

    if (!suggestion) return null;

    // Derived State
    const initialStart = new Date(suggestion.start);
    const initialEnd = suggestion.end ? new Date(suggestion.end) : dayjs(initialStart).add(60, 'minute').toDate();
    
    // Current State (User edits)
    const startDate = adjustedStart || initialStart;
    const durationMinutes = dayjs(initialEnd).diff(dayjs(initialStart), 'minute') || 60;
    const endDate = dayjs(startDate).add(durationMinutes, 'minute').toDate();

    const isWalk = type === 'walk';
    const title = isWalk ? 'Time for a Walk?' : (suggestion.title || 'Lunch (Suggested)');
    const eventTitle = isWalk ? 'Walk' : 'Lunch';
    const themeColor = isWalk ? 'emerald' : 'blue'; // tailwind colors need specific mapping or manual hex
    const iconName = isWalk ? 'walk' : 'restaurant';
    const themeColorHex = isWalk ? Palette[9] : Colors.primary;
    const bgColorClass = isWalk ? 'bg-success' : 'bg-primary';
    const iconBgClass = isWalk ? 'bg-success' : 'bg-primary';
    const confirmBtnClass = isWalk ? 'bg-success' : 'bg-primary';

    const handleConfirm = async () => {
        setLoading(true);
        try {
             // Determine target calendar
             let targetCalendarId = defaultCreateCalendarId;

             // Fallback to first visible calendar if not configured
             // This mimics the robust logic from LunchContextModal
             if (!targetCalendarId && visibleCalendarIds.length > 0) {
                 targetCalendarId = visibleCalendarIds[0];
             }
 
             if (!targetCalendarId) {
                 showAlert("Configuration Error", 'Please set a "Default to create" calendar in Settings.');
                 setLoading(false);
                 return;
             }
             
             const eventData: any = {
                title: eventTitle,
                startDate: startDate,
                endDate: endDate,
                timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                notes: suggestion.reason || 'Generated by AI Inbox'
            };

            // Add Default Invitee if present (mostly for Lunch)
            if (!isWalk && myEmails && myEmails.length > 0) {
                eventData.attendees = myEmails.map(email => ({
                    email: email,
                    role: 'attendee',
                    status: 'pending',
                    type: 'person'
                }));
            }

            await createCalendarEvent(targetCalendarId, eventData);
            
            onEventCreated();
            onClose();
        } catch (error) {
            console.error(`Failed to materialize ${type}:`, error);
            showError("Error", `Failed to schedule ${type}.`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
            <View className="flex-1 justify-center items-center bg-black/60 px-4">
                <BlurView intensity={20} className="absolute inset-0" />
                <View className="bg-background w-full max-w-sm rounded-3xl overflow-hidden border border-border shadow-xl">
                    
                    {/* Header */}
                    <View className={`${bgColorClass} p-6 items-center border-b border-border relative`}>
                        <CloseButton
                            onPress={onClose}
                            style={{ position: 'absolute', top: 16, right: 16, zIndex: 10 }}
                        />

                        <View className={`w-16 h-16 ${iconBgClass} rounded-full items-center justify-center mb-3 shadow-lg shadow-black/20`}>
                            <Ionicons name={iconName} size={32} color="white" />
                        </View>
                        <Text className="text-white text-xl font-bold">{title}</Text>
                        {suggestion.reason && (
                            <Text className="text-success text-center mt-1 text-sm font-medium">
                                {suggestion.reason}
                            </Text>
                        )}
                    </View>

                    {/* Time Selection */}
                    <View className="p-6 space-y-4">
                        <View className="flex-row justify-between items-center bg-surface/50 p-4 rounded-xl border border-border/50">
                            <View>
                                <Text className="text-text-tertiary text-xs uppercase tracking-wider font-bold mb-1">Suggested Time</Text>
                                <View className="flex-row items-baseline">
                                    <Text className="text-white text-lg font-semibold">
                                        {dayjs(startDate).format(timeFormatStr)}
                                    </Text>
                                    <Text className="text-secondary text-sm ml-1">
                                        - {dayjs(endDate).format(timeFormatStr)}
                                    </Text>
                                </View>
                            </View>
                            
                            {/* Button to trigger picker */}
                            <AppButton
                                title="Change"
                                variant="secondary"
                                size="sm"
                                rounding="md"
                                onPress={() => setShowPicker(true)}
                            />
                        </View>

                        {/* DateTimePicker - Conditionally rendered for Android */}
                        {showPicker && (
                             <DateTimePicker
                                value={startDate}
                                mode="time"
                                display="default"
                                onChange={(event, date) => {
                                    setShowPicker(false);
                                    if (event.type === 'set' && date) {
                                        setAdjustedStart(date);
                                    }
                                }}
                            />
                        )}

                        <View className="space-y-3 pt-2 flex-col gap-1">
                            <AppButton
                                icon="calendar"
                                title={isWalk ? 'Schedule Walk' : 'Schedule Lunch'}
                                variant={isWalk ? 'success' : 'primary'}
                                size="md"
                                onPress={handleConfirm}
                                loading={loading}
                            />

                            <AppButton
                                icon="close-circle-outline"
                                title={isWalk ? 'Dismiss for Today' : 'Skip Lunch'}
                                variant="ghost"
                                size="md"
                                onPress={() => {
                                    if (onDismiss) onDismiss();
                                    onClose();
                                }}
                            />
                        </View>
                    </View>
                </View>
            </View>
        </Modal>
    );
}
