import React, { useState, useEffect } from 'react';
import { View, Text, Modal, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import DateTimePicker from '@react-native-community/datetimepicker';
import dayjs from 'dayjs';
import { BlurView } from 'expo-blur';
import { useSettingsStore } from '../store/settings';
import { createCalendarEvent } from '../services/calendarService';
import { Colors, Palette } from './ui/design-tokens';

interface UnifiedSuggestionModalProps {
    visible: boolean;
    onClose: () => void;
    type: 'lunch' | 'walk';
    suggestion: {
        start: string | Date;
        end?: string | Date;
        reason?: string;
        title?: string;
    } | null;
    onEventCreated: () => void;
    onDismiss?: () => void; // For dismissing suggestions without creating
}

export function UnifiedSuggestionModal({ 
    visible, 
    onClose, 
    type, 
    suggestion, 
    onEventCreated, 
    onDismiss 
}: UnifiedSuggestionModalProps) {
    const { timeFormat, defaultCreateCalendarId, visibleCalendarIds, myEmails } = useSettingsStore();
    const timeFormatStr = timeFormat === '24h' ? 'HH:mm' : 'h:mm A';

    const [loading, setLoading] = useState(false);
    const [adjustedStart, setAdjustedStart] = useState<Date | null>(null);
    const [showPicker, setShowPicker] = useState(false);
    
    // Reset state when modal opens/closes
    useEffect(() => {
        if (visible) {
            setAdjustedStart(null);
            setLoading(false);
        }
    }, [visible]);

    if (!suggestion) return null;

    // Derived State
    const initialStart = new Date(suggestion.start);
    const initialEnd = suggestion.end ? new Date(suggestion.end) : dayjs(initialStart).add(60, 'minute').toDate();
    
    // Current State (User edits)
    const startDate = adjustedStart || initialStart;
    const durationMinutes = dayjs(initialEnd).diff(dayjs(initialStart), 'minute') || 60;
    const endDate = dayjs(startDate).add(durationMinutes, 'minute').toDate();

    const isWalk = type === 'walk';
    const title = isWalk ? 'Time for a Walk?' : (suggestion.title || 'Lunch (Suggested)');
    const eventTitle = isWalk ? 'Walk' : 'Lunch';
    const themeColor = isWalk ? 'emerald' : 'blue'; // tailwind colors need specific mapping or manual hex
    const iconName = isWalk ? 'walk' : 'restaurant';
    const themeColorHex = isWalk ? Palette[9] : Colors.primary;
    const bgColorClass = isWalk ? 'bg-emerald-600/20' : 'bg-blue-600/20';
    const iconBgClass = isWalk ? 'bg-emerald-500' : 'bg-blue-500';
    const confirmBtnClass = isWalk ? 'bg-emerald-500' : 'bg-blue-500';

    const handleConfirm = async () => {
        setLoading(true);
        try {
             // Determine target calendar
             let targetCalendarId = defaultCreateCalendarId;

             // Fallback to first visible calendar if not configured
             // This mimics the robust logic from LunchContextModal
             if (!targetCalendarId && visibleCalendarIds.length > 0) {
                 targetCalendarId = visibleCalendarIds[0];
             }
 
             if (!targetCalendarId) {
                 Alert.alert("Configuration Error", 'Please set a "Default to create" calendar in Settings.');
                 setLoading(false);
                 return;
             }
             
             const eventData: any = {
                title: eventTitle,
                startDate: startDate,
                endDate: endDate,
                timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                notes: suggestion.reason || 'Generated by AI Inbox'
            };

            // Add Default Invitee if present (mostly for Lunch)
            if (!isWalk && myEmails && myEmails.length > 0) {
                eventData.attendees = myEmails.map(email => ({
                    email: email,
                    role: 'attendee',
                    status: 'pending',
                    type: 'person'
                }));
            }

            await createCalendarEvent(targetCalendarId, eventData);
            
            onEventCreated();
            onClose();
        } catch (error) {
            console.error(`Failed to materialize ${type}:`, error);
            Alert.alert("Error", `Failed to schedule ${type}.`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
            <View className="flex-1 justify-center items-center bg-black/60 px-4">
                <BlurView intensity={20} className="absolute inset-0" />
                <View className="bg-slate-900 w-full max-w-sm rounded-3xl overflow-hidden border border-slate-700 shadow-xl">
                    
                    {/* Header */}
                    <View className={`${bgColorClass} p-6 items-center border-b border-slate-700 relative`}>
                        <TouchableOpacity 
                            onPress={onClose}
                            className="absolute top-4 right-4 z-10 p-1"
                        >
                            <Ionicons name="close" size={24} color="rgba(255,255,255,0.6)" />
                        </TouchableOpacity>

                        <View className={`w-16 h-16 ${iconBgClass} rounded-full items-center justify-center mb-3 shadow-lg shadow-black/20`}>
                            <Ionicons name={iconName} size={32} color="white" />
                        </View>
                        <Text className="text-white text-xl font-bold">{title}</Text>
                        {suggestion.reason && (
                            <Text className="text-emerald-200 text-center mt-1 text-sm font-medium">
                                {suggestion.reason}
                            </Text>
                        )}
                    </View>

                    {/* Time Selection */}
                    <View className="p-6 space-y-4">
                        <View className="flex-row justify-between items-center bg-slate-800/50 p-4 rounded-xl border border-slate-700/50">
                            <View>
                                <Text className="text-slate-400 text-xs uppercase tracking-wider font-bold mb-1">Suggested Time</Text>
                                <View className="flex-row items-baseline">
                                    <Text className="text-white text-lg font-semibold">
                                        {dayjs(startDate).format(timeFormatStr)}
                                    </Text>
                                    <Text className="text-slate-500 text-sm ml-1">
                                        - {dayjs(endDate).format(timeFormatStr)}
                                    </Text>
                                </View>
                            </View>
                            
                            {/* Button to trigger picker */}
                            <TouchableOpacity 
                                onPress={() => setShowPicker(true)}
                                className="bg-slate-700 px-4 py-2 rounded-lg"
                            >
                                <Text className="text-white font-medium">Change</Text>
                            </TouchableOpacity>
                        </View>

                        {/* DateTimePicker - Conditionally rendered for Android */}
                        {showPicker && (
                             <DateTimePicker
                                value={startDate}
                                mode="time"
                                display="default"
                                onChange={(event, date) => {
                                    setShowPicker(false);
                                    if (event.type === 'set' && date) {
                                        setAdjustedStart(date);
                                    }
                                }}
                            />
                        )}

                        <View className="space-y-3 pt-2 flex-col gap-1">
                             <TouchableOpacity
                                onPress={handleConfirm}
                                disabled={loading}
                                className={`${confirmBtnClass} py-3 rounded-xl flex-row justify-center items-center shadow-lg shadow-black/20`}
                            >
                                {loading ? (
                                    <ActivityIndicator color="white" />
                                ) : (
                                    <>
                                        <Ionicons name="calendar" size={20} color="white" className="mr-2" />
                                        <Text className="text-white font-bold text-base">
                                            {isWalk ? 'Schedule Walk' : 'Schedule Lunch'}
                                        </Text>
                                    </>
                                )}
                            </TouchableOpacity>

                            <TouchableOpacity
                                onPress={() => {
                                    if (onDismiss) onDismiss();
                                    onClose();
                                }}
                                className="bg-slate-800 py-3 rounded-xl flex-row justify-center items-center border border-slate-700"
                            >
                                <Ionicons name="close-circle-outline" size={20} color={Colors.text.tertiary} className="mr-2" />
                                <Text className="text-slate-400 font-semibold">
                                    {isWalk ? 'Dismiss for Today' : 'Skip Lunch'}
                                </Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>
            </View>
        </Modal>
    );
}
